apiVersion: v1
kind: Service
metadata:
  labels:
    name: giraphcluster-namenode
  name: giraphcluster-namenode
spec:
  type: LoadBalancer
  ports:
    - port: 8042
      targetPort: 8042
      protocol: TCP
      name: yarn-port-42
    - port: 8088
      targetPort: 8088
      protocol: TCP
      name: yarn-port-88
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: cluster-port-9000
    - port: 50070
      targetPort: 50070
      protocol: TCP
      name: hdfs-port-70
  selector:
    name: giraphcluster-namenode
